# Generated by Django 5.1.6 on 2025-03-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
