# Generated by Django 5.1.6 on 2025-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('IN_P', 'In_Progress'), ('CM', 'Completed')], default='PN', max_length=20),
        ),
    ]
