# Generated by Django 5.1.6 on 2025-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_subtask_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='subtask_type',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional')], default='Mandatory', max_length=20),
        ),
    ]
