# Generated by Django 5.2 on 2025-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
    ]
