# Generated by Django 5.2 on 2025-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='document',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='user_resume/'),
        ),
    ]
