# Generated by Django 5.1.6 on 2025-03-19 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_score', models.FloatField(default=0)),
                ('manual_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ManualReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('Complaint', 'Complaint'), ('Satisfaction', 'Satisfaction')], max_length=20)),
                ('score', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField()),
                ('progress', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Late', 'Late')], max_length=20)),
                ('system_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_score', models.FloatField(default=0)),
                ('manual_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='departments.departement')),
            ],
        ),
    ]
