# Generated by Django 5.1.6 on 2025-03-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_tasksubmission_delete_worksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
