# Generated by Django 5.1.6 on 2025-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_alter_tasksubmission_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='submission_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
