# Generated by Django 5.1.6 on 2025-03-27 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_alter_tasksubmission_submission_time'),
        ('tasks', '0005_alter_subtask_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now=True)),
                ('progress', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('On Time', 'On Time'), ('Late', 'Late')], max_length=20)),
                ('system_score', models.IntegerField(default=0)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtask_submissions', to=settings.AUTH_USER_MODEL)),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.subtask')),
            ],
        ),
    ]
